import type { FirmName } from '@/types/firmTypes';

export const mockData = [
  {
    firm: 'Alpha Capital Group' as FirmName,
    steps: '2 Steps',
    assetType: 'Forex',
    price: '$350.00',
    accountSize: '$100,000',
    profitSplit: '80%',
    profitTarget: '10%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5.00',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.5',
    link: 'https://alphagroup.com',
  },
  {
    firm: 'Apex Trader Funding' as FirmName,
    steps: 'Instant',
    assetType: 'Stocks',
    price: '$299.00',
    accountSize: '$50,000',
    profitSplit: '85%',
    profitTarget: '8%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '12%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$4.50',
    profitToTargetDrawdownRatio: '1.5:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.7',
    link: 'https://apextraderfunding.com',
  },
  {
    firm: 'Aqua Funded' as FirmName,
    steps: '3 Steps',
    assetType: 'Futures',
    price: '$235.00',
    accountSize: '$25,000',
    profitSplit: '70%',
    profitTarget: '6%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'None',
    commissionPerRoundLot: '$6.00',
    profitToTargetDrawdownRatio: '1.2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.3',
    link: 'https://aquafunded.com',
  },
  {
    firm: 'Audacity Capital' as FirmName,
    steps: '1 Step',
    assetType: 'Forex',
    price: '$450.00',
    accountSize: '$150,000',
    profitSplit: '90%',
    profitTarget: '12%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '15%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$6.50',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.6',
    link: '',
  },
  {
    firm: 'Blueberry Funded' as FirmName,
    steps: 'Instant',
    assetType: 'Crypto',
    price: '$99.00',
    accountSize: '$50,000',
    profitSplit: '50%',
    profitTarget: '5%',
    maxDailyLoss: '3%',
    maxTotalDrawdown: '7%',
    dailyDrawdownResetType: 'None',
    commissionPerRoundLot: '$5.00',
    profitToTargetDrawdownRatio: '1.1:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.4',
    link: '',
  },
  {
    firm: 'Breakout' as FirmName,
    steps: '2 Steps',
    assetType: 'Stocks',
    price: '$150.00',
    accountSize: '$100,000',
    profitSplit: '75%',
    profitTarget: '8%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$7.00',
    profitToTargetDrawdownRatio: '1.75:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.3',
    link: '',
  },
  {
    firm: 'CFT' as FirmName,
    steps: '3 Steps',
    assetType: 'Commodities',
    price: '$120.00',
    accountSize: '$70,000',
    profitSplit: '80%',
    profitTarget: '10%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '12%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5.50',
    profitToTargetDrawdownRatio: '1.8:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.5',
    link: '',
  },
  {
    firm: 'City Traders Imperium' as FirmName,
    steps: '1 Step',
    assetType: 'Indices',
    price: '$500.00',
    accountSize: '$100,000',
    profitSplit: '85%',
    profitTarget: '10%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$6.00',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.7',
    link: '',
  },
  {
    firm: 'E8Markets' as FirmName,
    steps: '2 Steps',
    assetType: 'Futures',
    price: '$400.00',
    accountSize: '$50,000',
    profitSplit: '75%',
    profitTarget: '7%',
    maxDailyLoss: '3%',
    maxTotalDrawdown: '7%',
    dailyDrawdownResetType: 'None',
    commissionPerRoundLot: '$5.00',
    profitToTargetDrawdownRatio: '1.3:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.1',
    link: '',
  },
  {
    firm: 'Earn2Trade' as FirmName,
    steps: '1 Step',
    assetType: 'Stocks',
    price: '$200.00',
    accountSize: '$25,000',
    profitSplit: '70%',
    profitTarget: '6%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$4.50',
    profitToTargetDrawdownRatio: '1.2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.4',
    link: '',
  },
  {
    firm: 'Finotive Funding' as FirmName,
    steps: '3 Steps',
    assetType: 'Forex',
    price: '$350.00',
    accountSize: '$80,000',
    profitSplit: '80%',
    profitTarget: '8%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$4.80',
    profitToTargetDrawdownRatio: '1.75:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.6',
    link: '',
  },
  {
    firm: 'For Traders' as FirmName,
    steps: 'Instant',
    assetType: 'Commodities',
    price: '$250.00',
    accountSize: '$100,000',
    profitSplit: '85%',
    profitTarget: '10%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5.50',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.5',
    link: '',
  },
  {
    firm: 'FTM' as FirmName,
    steps: '1 Step',
    assetType: 'Crypto',
    price: '$499.00',
    accountSize: '$150,000',
    profitSplit: '90%',
    profitTarget: '12%',
    maxDailyLoss: '6%',
    maxTotalDrawdown: '15%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$7.00',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.3',
    link: '',
  },
  {
    firm: 'FundedNext' as FirmName,
    steps: '2 Steps',
    assetType: 'Forex',
    price: '$400.00',
    accountSize: '$100,000',
    profitSplit: '80%',
    profitTarget: '10%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5.00',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.7',
    link: '',
  },
  {
    firm: 'Funded Trading Plus' as FirmName,
    steps: 'Instant',
    assetType: 'Stocks',
    price: '$275.00',
    accountSize: '$75,000',
    profitSplit: '85%',
    profitTarget: '7%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5.00',
    profitToTargetDrawdownRatio: '1.7:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.4',
    link: '',
  },
  {
    firm: 'Funding Pips' as FirmName,
    steps: '3 Steps',
    assetType: 'Indices',
    price: '$300.00',
    accountSize: '$50,000',
    profitSplit: '80%',
    profitTarget: '8%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'None',
    commissionPerRoundLot: '$5.50',
    profitToTargetDrawdownRatio: '1.5:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.5',
    link: '',
  },
  {
    firm: 'Funding Traders' as FirmName,
    steps: '2 Steps',
    assetType: 'Commodities',
    price: '$350.00',
    accountSize: '$100,000',
    profitSplit: '85%',
    profitTarget: '10%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5.50',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.5',
    link: '',
  },
  {
    firm: 'Fxify' as FirmName,
    steps: '1 Step',
    assetType: 'Futures',
    price: '$450.00',
    accountSize: '$150,000',
    profitSplit: '85%',
    profitTarget: '12%',
    maxDailyLoss: '6%',
    maxTotalDrawdown: '15%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$6.50',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.4',
    link: '',
  },
  {
    firm: 'Goat Funded Trader' as FirmName,
    steps: '3 Steps',
    assetType: 'Forex',
    price: '$199.00',
    accountSize: '$50,000',
    profitSplit: '75%',
    profitTarget: '8%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5.00',
    profitToTargetDrawdownRatio: '1.5:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.6',
    link: '',
  },
  {
    firm: 'Instant Funding' as FirmName,
    steps: 'Instant',
    assetType: 'Indices',
    price: '$350.00',
    accountSize: '$100,000',
    profitSplit: '80%',
    profitTarget: '10%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'None',
    commissionPerRoundLot: '$5.50',
    profitToTargetDrawdownRatio: '1.8:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.5',
    link: '',
  },
  {
    firm: 'Lark Funding' as FirmName,
    steps: '2 Steps',
    assetType: 'Stocks',
    price: '$400.00',
    accountSize: '$80,000',
    profitSplit: '85%',
    profitTarget: '9%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$4.50',
    profitToTargetDrawdownRatio: '1.75:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.7',
    link: '',
  },
  {
    firm: 'Ment Funding' as FirmName,
    steps: '3 Steps',
    assetType: 'Forex',
    price: '$299.00',
    accountSize: '$50,000',
    profitSplit: '75%',
    profitTarget: '8%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5.00',
    profitToTargetDrawdownRatio: '1.5:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.5',
    link: '',
  },
  {
    firm: 'MyFundedFX' as FirmName,
    steps: '1 Step',
    assetType: 'Crypto',
    price: '$400.00',
    accountSize: '$100,000',
    profitSplit: '80%',
    profitTarget: '8%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'None',
    commissionPerRoundLot: '$5.00',
    profitToTargetDrawdownRatio: '1.5:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.8',
    link: '',
  },
  {
    firm: 'QuantTekel' as FirmName,
    steps: '2 Steps',
    assetType: 'Indices',
    price: '$500.00',
    accountSize: '$150,000',
    profitSplit: '85%',
    profitTarget: '12%',
    maxDailyLoss: '6%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$6.00',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.7',
    link: '',
  },
  {
    firm: 'The5Percenters' as FirmName,
    steps: '3 Steps',
    assetType: 'Commodities',
    price: '$600.00',
    accountSize: '$100,000',
    profitSplit: '85%',
    profitTarget: '8%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5.50',
    profitToTargetDrawdownRatio: '1.8:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.6',
    link: '',
  },
  {
    firm: 'The Trading Pit' as FirmName,
    steps: 'Instant',
    assetType: 'Crypto',
    price: '$250.00',
    accountSize: '$25,000',
    profitSplit: '85%',
    profitTarget: '7%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'None',
    commissionPerRoundLot: '$5.50',
    profitToTargetDrawdownRatio: '1.7:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.1',
    link: '',
  },
  {
    firm: 'Topstep' as FirmName,
    steps: '3 Steps',
    assetType: 'Stocks',
    price: '$150.00',
    accountSize: '$150,000',
    profitSplit: '90%',
    profitTarget: '12%',
    maxDailyLoss: '6%',
    maxTotalDrawdown: '15%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$7.00',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.3',
    link: '',
  },
  {
    firm: 'Trade Day' as FirmName,
    steps: '2 Steps',
    assetType: 'Forex',
    price: '$350.00',
    accountSize: '$100,000',
    profitSplit: '85%',
    profitTarget: '10%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5.00',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.5',
    link: '',
  },
  {
    firm: 'Trade The Pool' as FirmName,
    steps: '1 Step',
    assetType: 'Futures',
    price: '$300.00',
    accountSize: '$75,000',
    profitSplit: '85%',
    profitTarget: '8%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'None',
    commissionPerRoundLot: '$5.00',
    profitToTargetDrawdownRatio: '1.6:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.5',
    link: '',
  },
];
