export const mockData = [
  {
    firm: 'FTMO',
    price: '$500',
    accountSize: '$100,000',
    profitSplit: '70%',
    profitTarget: '10%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.8',
    link: '',
  },
  {
    firm: 'MyForexFunds',
    price: '$299',
    accountSize: '$50,000',
    profitSplit: '85%',
    profitTarget: '8%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '12%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$4.5',
    profitToTargetDrawdownRatio: '1.5:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.7',
    link: '',
  },
  {
    firm: 'The5ers',
    price: '$235',
    accountSize: '$20,000',
    profitSplit: '50%',
    profitTarget: '6%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$6',
    profitToTargetDrawdownRatio: '1:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.5',
    link: '',
  },
  {
    firm: 'FundedNext',
    price: '$350',
    accountSize: '$80,000',
    profitSplit: '80%',
    profitTarget: '10%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$4',
    profitToTargetDrawdownRatio: '1.75:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.6',
    link: '',
  },
  {
    firm: 'BluFx',
    price: '$99',
    accountSize: '$50,000',
    profitSplit: '50%',
    profitTarget: '5%',
    maxDailyLoss: '3%',
    maxTotalDrawdown: '7%',
    dailyDrawdownResetType: 'None',
    commissionPerRoundLot: '$6.5',
    profitToTargetDrawdownRatio: '1:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.0',
    link: '',
  },
  {
    firm: 'TopStepTrader',
    price: '$150',
    accountSize: '$150,000',
    profitSplit: '90%',
    profitTarget: '12%',
    maxDailyLoss: '6%',
    maxTotalDrawdown: '15%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$7',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.3',
    link: '',
  },
  {
    firm: 'City Traders Imperium',
    price: '$399',
    accountSize: '$70,000',
    profitSplit: '80%',
    profitTarget: '10%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '12%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$4.8',
    profitToTargetDrawdownRatio: '1.8:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.4',
    link: '',
  },
  {
    firm: 'SurgeTrader',
    price: '$400',
    accountSize: '$100,000',
    profitSplit: '75%',
    profitTarget: '8%',
    maxDailyLoss: '4%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$5',
    profitToTargetDrawdownRatio: '2:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.2',
    link: '',
  },
  {
    firm: 'The Trading Pit',
    price: '$250',
    accountSize: '$25,000',
    profitSplit: '85%',
    profitTarget: '7%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '8%',
    dailyDrawdownResetType: 'None',
    commissionPerRoundLot: '$5.5',
    profitToTargetDrawdownRatio: '1.7:1',
    payoutFrequency: '30 Days',
    trustPilotRating: '4.1',
    link: '',
  },
  {
    firm: 'True Forex Funds',
    price: '$500',
    accountSize: '$100,000',
    profitSplit: '80%',
    profitTarget: '8%',
    maxDailyLoss: '5%',
    maxTotalDrawdown: '10%',
    dailyDrawdownResetType: 'Daily',
    commissionPerRoundLot: '$4.2',
    profitToTargetDrawdownRatio: '1.5:1',
    payoutFrequency: '14 Days',
    trustPilotRating: '4.9',
    link: '',
  },
];
